[program:mysql]
command=/bin/bash /restart_mysql.sh
user=root
autostart=true
autorestart=true
startsecs=60
startretries=5
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor_mysql_info.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisor_mysql_error.log
stderr_logfile_maxbytes=0