[program:apache2]
command=/bin/bash -c "source /etc/apache2/envvars && exec /usr/sbin/apache2ctl -D FOREGROUND"
user=root
startsecs=5
startretries=3
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor_apache2_info.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisor_apache2_error.log
stderr_logfile_maxbytes=0